apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-postgres-exporter
type: Opaque
data:
  DATABASE_URI_EXPORTER: {{ printf "postgresql://%s:%s@%s:%s/%s?sslmode=disable" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
