apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-exporter
  labels:
    {{- include "hw3-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres_exporter.service.type }}
  ports:
    - port: {{ .Values.postgres_exporter.service.port }}
      targetPort: db-metrics
      protocol: TCP
      name: db-metrics
  selector:
    {{- include "hw3-chart.selectorLabels" . | nindent 4 }}
